# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Detail_Acara.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QDateEdit, QTimeEdit, QTextEdit

class Ui_Detail_Acara(object):
    def initialize(self, acara_controller, nama_acara):
        self.acara_controller = acara_controller
        self.nama_acara = nama_acara
        self.original_data = None
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(731, 531)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 80, 321, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dateEdit_2 = QtWidgets.QDateEdit(Form)
        self.dateEdit_2.setGeometry(QtCore.QRect(380, 150, 161, 41))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 150, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.timeEdit_2 = QtWidgets.QTimeEdit(Form)
        self.timeEdit_2.setGeometry(QtCore.QRect(380, 220, 161, 41))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 290, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(380, 290, 321, 141))
        self.textEdit_2.setUndoRedoEnabled(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 460, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 460, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.clicked.connect(self.handle_edit_button)
        self.pushButton_2.clicked.connect(self.handle_delete_button)
        print("LineEdit_2 found:", hasattr(self, 'lineEdit_2'))
        print("DateEdit_2 found:", hasattr(self, 'dateEdit_2'))
        print("TimeEdit_2 found:", hasattr(self, 'timeEdit_2'))
        print("TextEdit_2 found:", hasattr(self, 'textEdit_2'))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def initialize(self, acara_controller, nama_acara):
        self.acara_controller = acara_controller
        self.nama_acara = nama_acara
        self.original_data = None

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detail Acara"))
        self.label.setText(_translate("Form", "Detail Acara:"))
        self.label_7.setText(_translate("Form", "Nama Acara:"))
        self.label_8.setText(_translate("Form", "Tanggal:"))
        self.label_4.setText(_translate("Form", "Waktu:"))
        self.label_9.setText(_translate("Form", "Deskripsi Acara:"))
        self.pushButton.setText(_translate("Form", "Edit Acara"))
        self.pushButton_2.setText(_translate("Form", "Hapus Acara"))

    # Perubahan pada metode setLineEditValues
    def setLineEditValues(self, data):
        print("Data diatur ke Detail_Acara:", data)  # Debug line

        self.lineEdit_2.setText(data.get("Nama Acara", ""))
        self.dateEdit_2.setDate(data.get("Tanggal", QtCore.QDate.currentDate()))
        self.timeEdit_2.setTime(data.get("Waktu", QtCore.QTime.currentTime()))
        self.textEdit_2.setPlainText(data.get("Deskripsi Acara", ""))

    # Tambahkan fungsi untuk menangani tombol Edit Acara
    def handle_edit_button(self):
        # Mengambil nilai dari elemen UI
        updated_data = {
            "Nama_Acara": self.lineEdit_2.text(),
            "Tanggal": self.dateEdit_2.date().toString("yyyy-MM-dd"),
            "Waktu": self.timeEdit_2.time().toString("hh:mm:ss"),
            "Deskripsi_Acara": self.textEdit_2.toPlainText(),
        }

        # Update data di database menggunakan AcaraController
        self.acara_controller.update_data_in_database(self.nama_acara, updated_data)

        # Tutup dialog setelah selesai mengedit (if applicable)
        if hasattr(self, 'parent_widget') and self.parent_widget:
            self.parent_widget.accept()
    
    def set_parent_widget(self, parent_widget):
        self.parent_widget = parent_widget

    # New method for handling the "Hapus Acara" button click
    def handle_delete_button(self):
        # Confirmation dialog before deleting the event
        reply = QtWidgets.QMessageBox.question(
            None,
            'Hapus Acara',
            'Apakah Anda yakin ingin menghapus acara ini?',
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            # Call the delete method from the controller
            self.acara_controller.delete_data_in_database(self.nama_acara)

            # Close the detail window or perform any other actions needed
            if hasattr(self, 'parent_widget') and self.parent_widget:
                self.parent_widget.accept()



    




